version: 2
updates:
- package-ecosystem: pip
  directory: "/api"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  allow:
  - dependency-type: direct
  - dependency-type: indirect
- package-ecosystem: npm
  directory: "/frontend-vue"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@vue/compiler-sfc"
    versions:
    - 3.0.10
    - 3.0.9
  - dependency-name: vue
    versions:
    - 3.0.10
    - 3.0.9
  - dependency-name: vite
    versions:
    - 2.0.4
    - 2.1.3
    - 2.1.4
  - dependency-name: "@vitejs/plugin-vue"
    versions:
    - 1.2.0
  - dependency-name: "@vuedx/typecheck"
    versions:
    - 0.6.3
