version: 2
updates:
- package-ecosystem: pip
  directory: "/api"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  allow:
  - dependency-type: direct
  - dependency-type: indirect
- package-ecosystem: npm
  directory: "/frontend-vue"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
